Repository lunarphp/lunar, pull requests merged in 2022-09, with the labels that each got.

#500 Extracted variant side menu to it's own component
  packages/admin/resources/views/livewire/components/products/variants/show.blade.php
  packages/admin/resources/views/livewire/components/products/variants/side-menu.blade.php
  packages/admin/src/AdminHubServiceProvider.php
  packages/admin/src/Http/Livewire/Components/Products/Variants/VariantSideMenu.php
Labels: bug

#416 Model Factory Trait
  docs/src/extending/models.md
  packages/admin/src/Http/Livewire/Components/ActivityLogFeed.php
  packages/core/src/Base/BaseModel.php
  packages/core/src/Base/ModelManifest.php
  packages/core/src/Base/ModelManifestInterface.php
  packages/core/src/Base/Traits/HasModelExtending.php
  packages/core/src/Facades/ModelManifest.php
  packages/core/src/GetCandyServiceProvider.php
  packages/core/tests/Stubs/Models/Product.php
  packages/core/tests/Stubs/Models/ProductOption.php
  packages/core/tests/Stubs/Models/ProductSwapModel.php
  packages/core/tests/Stubs/Models/SearchableTrait.php
  packages/core/tests/Stubs/Models/SizesTrait.php
  packages/core/tests/Unit/Base/BaseModelTest.php
  packages/core/tests/Unit/Base/Extendable/ExtendScoutTest.php
  packages/core/tests/Unit/Base/Extendable/ExtendTraitTest.php
  packages/core/tests/Unit/Base/Extendable/ExtendableTestCase.php
  packages/core/tests/Unit/Base/Extendable/MorphTest.php
  packages/core/tests/Unit/Base/Extendable/SwapTest.php
  packages/core/tests/Unit/Base/ModelManifestTest.php
  packages/core/tests/Unit/Base/Traits/HasModelExtendingTest.php
  packages/core/tests/Unit/Traits/HasUrlsTraitTest.php
Labels: feature

#279 Package assets
  docs/src/.vuepress/config.js
  docs/src/extending/assets.md
  docs/src/extending/field-types.md
  packages/admin/resources/views/layouts/app.blade.php
  packages/admin/routes/includes/assets.php
  packages/admin/routes/web.php
  packages/admin/src/Assets/Asset.php
  packages/admin/src/Assets/Script.php
  packages/admin/src/Assets/Style.php
  packages/admin/src/GetCandyHub.php
  packages/admin/src/Http/Controllers/ScriptsController.php
  packages/admin/src/Http/Controllers/StylesController.php
  packages/admin/tests/Feature/Http/Controllers/ScriptsControllerTest.php
  packages/admin/tests/Feature/Http/Controllers/StylesControllerTest.php
  packages/admin/tests/Unit/GetCandyHubTest.php
Labels: feature

#488 Hotfix - Tweak migrations and add test
  packages/core/database/migrations/2022_01_12_100000_add_columns_to_attributes_table.php
  packages/core/database/migrations/2022_01_18_100001_add_customer_id_to_orders_table.php
  packages/core/database/migrations/2022_03_11_100000_remove_formatting_columns_from_currencies_table.php
  packages/core/database/migrations/2022_03_17_100000_add_fields_to_transactions_table.php
  packages/core/tests/Unit/MigrationTest.php
Labels: bug

#497 Fix - Fix url management
  packages/admin/CHANGELOG.md
  packages/admin/resources/views/partials/urls.blade.php
  packages/admin/src/Http/Livewire/Traits/HasUrls.php
Labels: bug

#499 Laravel Pint (code style)
  .github/workflows/laravel-pint-code-style.yml
  .styleci.yml
  composer.json
  packages/admin/src/Http/Livewire/Components/Products/ProductsIndex.php
  packages/admin/src/Http/Livewire/Components/Settings/Tags/TagShow.php
  packages/admin/src/Http/Livewire/Traits/HasSlots.php
  packages/admin/src/Http/Livewire/Traits/WithAttributes.php
  packages/admin/src/Views/Components/MenuList.php
  pint.json
Labels: feature

#476 Hotfix - Fix activity log form on variants
  packages/admin/CHANGELOG.md
  packages/admin/resources/views/livewire/components/products/variants/show.blade.php
  packages/admin/src/Base/ActivityLog/Manifest.php
  packages/core/CHANGELOG.md
Labels: bug

#477 Enhancement - Fix variant image duplication
  packages/admin/resources/lang/en/partials.php
  packages/admin/resources/views/livewire/components/products/variants/show.blade.php
  packages/admin/resources/views/livewire/components/products/variants/side-menu.blade.php
  packages/admin/resources/views/partials/image-manager.blade.php
  packages/admin/resources/views/partials/products/variants/image.blade.php
  packages/admin/src/Http/Livewire/Components/Products/Variants/VariantShow.php
  packages/admin/src/Http/Livewire/Traits/HasImages.php
  packages/core/database/migrations/2022_08_09_100000_create_media_variant_table.php
  packages/core/src/Models/ProductVariant.php
Labels: enhancement

#474 Manage brands
  packages/admin/resources/lang/en/catalogue.php
  packages/admin/resources/lang/en/components.php
  packages/admin/resources/lang/en/menu.php
  packages/admin/resources/lang/en/notifications.php
  packages/admin/resources/lang/en/partials.php
  packages/admin/resources/views/livewire/components/brands/index.blade.php
  packages/admin/resources/views/livewire/components/brands/show.blade.php
  packages/admin/resources/views/livewire/components/products/index.blade.php
  packages/admin/resources/views/livewire/pages/brands/index.blade.php
  packages/admin/resources/views/livewire/pages/brands/show.blade.php
  packages/admin/resources/views/partials/forms/brand.blade.php
  packages/admin/resources/views/partials/products/editing/basic-information.blade.php
  packages/admin/routes/includes/brands.php
  packages/admin/routes/web.php
  packages/admin/src/AdminHubServiceProvider.php
  packages/admin/src/Http/Livewire/Components/Brands/BrandShow.php
  packages/admin/src/Http/Livewire/Components/Brands/BrandsIndex.php
  packages/admin/src/Http/Livewire/Components/Products/AbstractProduct.php
  packages/admin/src/Http/Livewire/Pages/Brands/BrandShow.php
  packages/admin/src/Http/Livewire/Pages/Brands/BrandsIndex.php
  packages/admin/src/Http/Livewire/Traits/SearchesProducts.php
  packages/admin/src/Menu/SidebarMenu.php
  packages/admin/tests/Feature/Http/Livewire/Pages/Products/ProductShowTest.php
  packages/admin/tests/Unit/Http/Livewire/Components/Products/ProductShowTest.php
  packages/core/database/factories/BrandFactory.php
  packages/core/database/migrations/2022_08_09_100001_create_brands_table.php
  packages/core/database/migrations/2022_08_09_100002_add_brand_id_to_products_table.php
  packages/core/database/state/EnsureBrandsAreUpgraded.php
  packages/core/src/GetCandyServiceProvider.php
  packages/core/src/Models/Brand.php
  packages/core/src/Models/Product.php
  packages/core/tests/Unit/Models/BrandTest.php
Labels: enhancement

#535 Add slots to customer show
  packages/admin/resources/views/livewire/components/customers/show.blade.php
  packages/admin/src/Http/Livewire/Components/Customers/CustomerShow.php
Labels: enhancement
