Repository lunarphp/lunar, pull requests merged in 2023-12, with the labels that each got.

#1383 Monorepo splitting updates
  .github/workflows/split_packages.yml
  monorepo-builder.php
Labels: chore

#1379 Auto-fix Pint Styling
  .github/workflows/fix-code-style.yml
  .github/workflows/laravel-pint-code-style.yml
  composer.json
  packages/admin/src/Filament/Resources/CollectionGroupResource.php
Labels: chore

#1388 Run tests on push
  .github/workflows/admin_tests.yml
  .github/workflows/core_tests.yml
  .github/workflows/fix-code-style.yml
  .github/workflows/scout_db_mysql_tests.yml
  .github/workflows/scout_db_postgres_tests.yml
  .github/workflows/static-analysis.yml
  .github/workflows/table_rate_shipping_tests.yml
  packages/core/database/state/ConvertTaxbreakdown.php
  packages/core/src/Models/Product.php
Labels: chore

#1394 fix creating product options in hub
  packages/admin/tests/Unit/Http/Livewire/Components/Settings/Product/ProductOptionCreateTest.php
  packages/core/src/Models/ProductOption.php
Labels: bug

#1402 Fix creating product options values in hub
  packages/admin/tests/Unit/Http/Livewire/Components/Settings/Product/ProductOptionValueCreateTest.php
  packages/core/src/Models/ProductOptionValue.php
Labels: bug

#1403 Update link to admin docs on index page
  docs/index.md
Labels: documentation

#1410 add listener to hub activityLogFeed
  packages/admin/src/Http/Livewire/Components/ActivityLogFeed.php
Labels: enhancement
