Repository lunarphp/lunar, pull requests merged in 2024-01, with the labels that each got.

#1441 Feature - Status editing updates
  composer.json
  packages/admin/composer.json
  packages/admin/resources/lang/en/product.php
  packages/admin/src/Filament/Resources/ProductResource.php
  packages/admin/src/Filament/Resources/ProductResource/Pages/EditProduct.php
  tests/admin/TestCase.php
Labels: enhancement

#1397 Fix dark mode collection
  packages/admin/resources/views/components/collections/nested-set-item.blade.php
Labels: bug

#1422 Collection more actions button not to show on hover
  packages/admin/resources/views/components/collections/nested-set-item.blade.php
Labels: enhancement

#1408 Feature - Order status emails
  packages/admin/resources/lang/en/actions.php
  packages/admin/resources/lang/en/order.php
  packages/admin/resources/views/forms/components/mailer-select.blade.php
  packages/admin/resources/views/partials/mail/mail-preview.blade.php
  packages/admin/src/Filament/Resources/OrderResource.php
  packages/admin/src/Filament/Resources/OrderResource/Pages/ManageOrder.php
  packages/admin/src/Support/Actions/Orders/UpdateStatusAction.php
  packages/admin/src/Support/Actions/Orders/UpdateStatusBulkAction.php
  packages/admin/src/Support/Actions/Traits/UpdatesOrderStatus.php
  packages/admin/src/Support/Forms/Components/MailerSelect.php
Labels: enhancement

#1426 Fix: missing order address attribute
  packages/core/src/Models/OrderAddress.php
Labels: bug

#1434 Fix: Error selecting applicable discounts
  packages/core/src/Managers/DiscountManager.php
Labels: bug

#1429 Docs: fix example usage of addLines
  docs/core/reference/carts.md
Labels: documentation

#1399 Make product list on full with size as order list
  packages/admin/src/Filament/Resources/OrderResource/Pages/ListOrders.php
  packages/admin/src/Filament/Resources/ProductResource/Pages/ListProducts.php
Labels: enhancement

#1452 Feature - Restore legacy informations in display list
  packages/admin/resources/lang/en/brand.php
  packages/admin/resources/lang/en/producttype.php
  packages/admin/src/Filament/Resources/BrandResource.php
  packages/admin/src/Filament/Resources/ProductTypeResource.php
Labels: enhancement

#1431 Fix - Multiple call permission manifest
  packages/admin/src/LunarPanelProvider.php
Labels: enhancement

#1427 Fix - Translation customer widget
  packages/admin/resources/lang/en/widgets.php
  packages/admin/src/Filament/Resources/CustomerResource/Widgets/CustomerStatsOverviewWidget.php
Labels: bug

#1416 Feature - Brand custom attribute editing
  packages/admin/src/Filament/Resources/BrandResource.php
Labels: enhancement

#1317 Fix order activity timeline blank entries
  packages/core/src/Base/Traits/LogsActivity.php
  packages/core/src/Models/Order.php
Labels: bug

#1349 Update dotfiles
  .editorconfig
  .gitattributes
  .gitignore
  packages/admin/.gitattributes
  packages/core/.gitattributes
  utils/livewire-tables/.gitattributes
  utils/scout-database-engine/.gitattributes
Labels: chore

#1406 Feature - Global search
  packages/admin/resources/lang/en/customer.php
  packages/admin/src/Filament/Resources/BrandResource.php
  packages/admin/src/Filament/Resources/CollectionResource.php
  packages/admin/src/Filament/Resources/CustomerResource.php
  packages/admin/src/Filament/Resources/OrderResource.php
  packages/admin/src/Filament/Resources/ProductResource.php
  packages/admin/src/Support/Resources/BaseResource.php
  tests/admin/Feature/Filament/Panel/GlobalSearch/GlobalSearchTest.php
  tests/admin/Feature/Filament/Resources/BrandResource/Actions/SearchTest.php
  tests/admin/Feature/Filament/Resources/ProductResource/Actions/SearchTest.php
Labels: enhancement

#1421 Feature - Product tag editing
  packages/admin/resources/lang/en/components.php
  packages/admin/resources/lang/en/order.php
  packages/admin/resources/views/infolists/components/tags.blade.php
  packages/admin/resources/views/livewire/components/tags.blade.php
  packages/admin/src/Filament/Resources/OrderResource/Pages/ManageOrder.php
  packages/admin/src/Filament/Resources/ProductResource.php
  packages/admin/src/Livewire/Components/Tags.php
  packages/admin/src/Support/Forms/Components/Tags.php
  packages/admin/src/Support/Infolists/Components/Tags.php
  tests/admin/Feature/Filament/Resources/OrderResource/Pages/ManageOrderTest.php
  tests/admin/Unit/Livewire/TagsComponentTest.php
Labels: enhancement

#1435 Update commands to use new command components
  packages/core/src/Console/Commands/AddonsDiscover.php
  packages/core/src/Console/Commands/Import/AddressData.php
  packages/core/src/Console/Commands/MigrateGetCandy.php
  packages/core/src/Console/Commands/Orders/SyncNewCustomerOrders.php
  packages/core/src/Console/Commands/ScoutIndexerCommand.php
  packages/core/src/Console/InstallLunar.php
Labels: enhancement

#1475 Feature - Support of widget on a resource page
  docs/admin/extending/pages.md
  packages/admin/src/LunarPanelManager.php
  packages/admin/src/Support/Pages/BaseCreateRecord.php
  packages/admin/src/Support/Pages/BaseEditRecord.php
  packages/admin/src/Support/Pages/BaseListRecords.php
  packages/admin/src/Support/Pages/Concerns/ExtendsFooterWidgets.php
  packages/admin/src/Support/Pages/Concerns/ExtendsHeaderWidgets.php
Labels: enhancement

#1478 Feature - Add helper text below render attribute
  packages/admin/resources/lang/en/attribute.php
  packages/admin/src/Filament/Resources/AttributeGroupResource/RelationManagers/AttributesRelationManager.php
  packages/admin/src/Support/FieldTypes/Dropdown.php
  packages/admin/src/Support/FieldTypes/File.php
  packages/admin/src/Support/FieldTypes/ListField.php
  packages/admin/src/Support/FieldTypes/TextField.php
  packages/admin/src/Support/FieldTypes/Toggle.php
  packages/admin/src/Support/FieldTypes/TranslatedText.php
  packages/admin/src/Support/FieldTypes/YouTube.php
  packages/core/database/factories/AttributeFactory.php
  packages/core/database/migrations/2024_01_11_100000_add_description_to_attributes_table.php
  packages/core/src/Models/Attribute.php
  tests/admin/Feature/Filament/Resources/CollectionResources/Pages/ManageCollectionChildrenTest.php
  tests/admin/Feature/Filament/Resources/ProductResource/ListProductsTest.php
  tests/core/Unit/Models/AttributeTest.php
Labels: enhancement

#1484 Fix - Query scout database engine #1355
  utils/scout-database-engine/src/DatabaseEngine.php
Labels: bug

#1498 Feature - Add new ViewPageExtension to authorize extend headers actions of ViewRecord
  docs/admin/extending/pages.md
  packages/admin/src/Filament/Resources/ActivityResource/Pages/ViewActivity.php
  packages/admin/src/Filament/Resources/OrderResource/Pages/ManageOrder.php
  packages/admin/src/Support/Extending/ViewPageExtension.php
  packages/admin/src/Support/Pages/BaseViewRecord.php
Labels: enhancement

#1510 Feature - Change default Chart to area mode
  packages/admin/src/Filament/Widgets/Dashboard/Orders/AverageOrderValueChart.php
  packages/admin/src/Filament/Widgets/Dashboard/Orders/OrderTotalsChart.php
  packages/admin/src/Filament/Widgets/Dashboard/Orders/OrdersSalesChart.php
Labels: enhancement

#1520 fix migration for product option relation
  packages/core/database/migrations/2024_01_16_100010_update_product_option_relations.php
Labels: bug

#1521 remove lazy load for page with only relation manager or widget
  packages/admin/src/Filament/Resources/ProductResource/RelationManagers/CustomerGroupRelationManager.php
  packages/admin/src/Filament/Resources/ProductResource/Widgets/ProductOptionsWidget.php
  packages/admin/src/Support/RelationManagers/ChannelRelationManager.php
  packages/admin/src/Support/RelationManagers/MediaRelationManager.php
Labels: enhancement
