Repository lunarphp/lunar, pull requests merged in 2024-02, with the labels that each got.

#1525 Fix - Create a child collection
  packages/admin/src/Support/Actions/Traits/CreatesChildCollections.php
Labels: bug

#1526 Feat - Rename Tier to Quantity Break
  docs/core/reference/pricing.md
  docs/core/reference/products.md
  docs/core/upgrading.md
  packages/admin/resources/lang/en/relationmanagers.php
  packages/admin/src/Filament/Resources/ProductResource/Pages/ListProducts.php
  packages/admin/src/Filament/Resources/ProductResource/Pages/ManageProductPricing.php
  packages/admin/src/Filament/Resources/ProductVariantResource/Pages/ManageVariantPricing.php
  packages/core/database/migrations/2024_01_31_100000_update_tier_to_quantity_break_on_prices_table.php
  packages/core/src/Base/DataTransferObjects/PricingResponse.php
  packages/core/src/Base/Traits/HasPrices.php
  packages/core/src/Managers/PricingManager.php
  packages/core/src/Models/Price.php
  packages/table-rate-shipping/resources/lang/en/relationmanagers.php
  packages/table-rate-shipping/resources/views/partials/ship-by-total.blade.php
  packages/table-rate-shipping/resources/views/shipping-methods/ship-by.blade.php
  packages/table-rate-shipping/src/Drivers/ShippingMethods/ShipBy.php
  packages/table-rate-shipping/src/Filament/Resources/ShippingZoneResource/Pages/ManageShippingRates.php
  tests/admin/Feature/Filament/Resources/ProductResource/Pages/ManageProductPricingTest.php
  tests/core/Unit/Actions/Carts/AddOrUpdatePurchasableTest.php
  tests/core/Unit/Actions/Carts/CalculateLineTest.php
  tests/core/Unit/Actions/Carts/CreateOrderTest.php
  tests/core/Unit/Actions/Carts/GenerateFingerprintTest.php
  tests/core/Unit/Actions/Carts/GetExistingCartLineTest.php
  tests/core/Unit/Actions/Carts/MergeCartTest.php
  tests/core/Unit/Actions/Carts/RemovePurchasableTest.php
  tests/core/Unit/Actions/Carts/UpdateCartLineTest.php
  tests/core/Unit/Actions/Collections/SortProductsByPriceTest.php
  tests/core/Unit/Base/ShippingManifestTest.php
  tests/core/Unit/Base/Traits/CachesPropertiesTest.php
  tests/core/Unit/DiscountTypes/AmountOffTest.php
  tests/core/Unit/DiscountTypes/BuyXGetYTest.php
  tests/core/Unit/Jobs/Collections/UpdateProductPositionsTest.php
  tests/core/Unit/Managers/DiscountManagerTest.php
  tests/core/Unit/Managers/PricingManagerTest.php
  tests/core/Unit/Models/CartTest.php
  tests/core/Unit/Models/PriceTest.php
  tests/core/Unit/Models/ProductVariantTest.php
  tests/core/Unit/Pipelines/Cart/ApplyShippingTest.php
  tests/core/Unit/Pipelines/Cart/CalculateLinesTest.php
  tests/core/Unit/Pipelines/Order/Creation/CleanUpOrderLinesTest.php
  tests/core/Unit/Pipelines/Order/Creation/CreateOrderLinesTest.php
  tests/core/Unit/Pipelines/Order/Creation/FillOrderFromCartTest.php
  tests/shipping/TestUtils.php
  tests/shipping/Unit/Drivers/ShippingMethods/FlatRateTest.php
  tests/shipping/Unit/Drivers/ShippingMethods/ShipByTest.php
  tests/shipping/Unit/Managers/ShippingManagerTest.php
  tests/shipping/Unit/Resolvers/ShippingOptionResolverTest.php
  tests/shipping/Unit/Resolvers/ShippingRateResolverTest.php
Labels: enhancement

#1505 Feature - Field translated text
  packages/admin/resources/lang/en/fieldtypes.php
  packages/admin/resources/views/forms/components/translated-text.blade.php
  packages/admin/src/Filament/Resources/AttributeGroupResource.php
  packages/admin/src/Filament/Resources/AttributeGroupResource/RelationManagers/AttributesRelationManager.php
  packages/admin/src/Filament/Resources/ProductOptionResource.php
  packages/admin/src/Filament/Resources/ProductOptionResource/RelationManagers/ValuesRelationManager.php
  packages/admin/src/Filament/Resources/ProductResource.php
  packages/admin/src/Filament/Resources/ProductResource/Pages/ListProducts.php
  packages/admin/src/Support/Actions/Collections/CreateChildCollection.php
  packages/admin/src/Support/Actions/Collections/CreateRootCollection.php
  packages/admin/src/Support/Actions/Traits/CreatesChildCollections.php
  packages/admin/src/Support/FieldTypes/TranslatedText.php
  packages/admin/src/Support/Forms/Components/TranslatedRichEditor.php
  packages/admin/src/Support/Forms/Components/TranslatedText.php
  packages/admin/src/Support/Forms/Components/TranslatedTextInput.php
  packages/admin/src/Support/Synthesizers/TranslatedTextSynth.php
  packages/admin/src/Support/Tables/Actions/Collections/CreateChildCollection.php
  packages/core/src/Models/ProductOption.php
  tests/admin/Feature/Filament/Resources/AttributeGroupResource/Pages/EditAttributeGroupTest.php
  tests/admin/Feature/Filament/Resources/AttributeGroupResource/RelationManagers/AttributesRelationManagerTest.php
  tests/admin/Feature/Filament/Resources/CollectionResources/Pages/ManageCollectionChildrenTest.php
  tests/admin/Feature/Filament/Resources/ProductResource/ListProductsTest.php
  tests/admin/Feature/Filament/Resources/ProductResource/Widgets/CollectionTreeViewTest.php
Labels: enhancement

#1479 Remove Scout driver
  .github/workflows/scout_db_mysql_tests.yml
  .github/workflows/scout_db_postgres_tests.yml
  packages/scout-database-engine/.gitignore
  packages/scout-database-engine/LICENSE.md
  packages/scout-database-engine/README.md
  packages/scout-database-engine/composer.json
  packages/scout-database-engine/database/migrations/2022_08_30_000000_create_search_index_table.php
  packages/scout-database-engine/phpunit.xml.dist
  packages/scout-database-engine/src/DatabaseEngine.php
  packages/scout-database-engine/src/ScoutDatabaseServiceProvider.php
  packages/scout-database-engine/src/SearchIndex.php
  phpunit.xml
  tests/scout-database-engine/Feature/.gitkeep
  tests/scout-database-engine/Stubs/Post.php
  tests/scout-database-engine/TestCase.php
  tests/scout-database-engine/TestServiceProvider.php
  tests/scout-database-engine/Unit/IndexerTest.php
  tests/scout-database-engine/Unit/SearchIndexTest.php
  tests/scout-database-engine/Unit/SearchTest.php
  tests/scout-database-engine/database/migrations/2022_08_31_000000_create_posts_table.php
Labels: chore
